#!/usr/bin/env bash
# Sync this repository to a cluster host and write job.slurm for Slurm.
# Usage:
#   ./deploy_to_cluster.sh user@cluster.example.edu [REMOTE_DIR]
# Environment (optional):
#   REMOTE_DIR      — default second arg or ~/research_deploy
#   RSYNC_EXTRA     — extra rsync args (e.g. --dry-run); word-split on spaces
#   SLURM_PARTITION, SLURM_ACCOUNT, SLURM_GRES — optional #SBATCH lines
#   SLURM_TIME      — walltime (default: 08:00:00)
#   SLURM_CPUS      — CPUs per task (default: 4)
#   SLURM_MEM       — memory (default: 32G)
#   PYTHON_BIN      — python on remote for venv (default: python3)
#   CONDA_ENV       — if set, conda activate that env then pip install (instead of venv)

set -euo pipefail

usage() {
  echo "Usage: $0 <user@host> [REMOTE_DIR]" >&2
  echo "  REMOTE_DIR defaults to ~/research_deploy" >&2
  exit 1
}

if [[ $# -lt 1 ]]; then
  usage
fi

REMOTE_HOST="$1"
REMOTE_DIR="${2:-${REMOTE_DIR:-~/research_deploy}}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JOB_SLURM="${SCRIPT_DIR}/job.slurm"

# If you passed an unquoted ~/path, your *local* shell expanded it to $HOME/...
# Use quotes for a remote home-relative path, e.g.  ./deploy_to_cluster.sh me@h '~/code'
if [[ "${REMOTE_DIR}" == "${HOME}/"* ]]; then
  echo "Warning: REMOTE_DIR looks like a local absolute path (${REMOTE_DIR})." >&2
  echo "  For a path under your home on the cluster, pass it quoted: '~/subdir'" >&2
fi

SLURM_TIME="${SLURM_TIME:-08:00:00}"
SLURM_CPUS="${SLURM_CPUS:-4}"
SLURM_MEM="${SLURM_MEM:-32G}"
PYTHON_BIN="${PYTHON_BIN:-python3}"

echo "Remote: ${REMOTE_HOST}:${REMOTE_DIR}"
echo "Local source: ${SCRIPT_DIR}"

emit_remote_cd() {
  case "${REMOTE_DIR}" in
  ~)
    echo "cd ~" ;;
  ~/*)
    # Remote shell expands ~ for the job user.
    echo "cd ${REMOTE_DIR}" ;;
  *)
    printf 'cd "%s"\n' "${REMOTE_DIR}" ;;
  esac
}

{
  cat <<HEADER
#!/bin/bash
# Generated by deploy_to_cluster.sh — re-run deploy to refresh paths and SBATCH lines.
#SBATCH --job-name=research-benchmarks
#SBATCH --output=slurm-%x-%j.out
#SBATCH --error=slurm-%x-%j.err
#SBATCH --time=${SLURM_TIME}
#SBATCH --cpus-per-task=${SLURM_CPUS}
#SBATCH --mem=${SLURM_MEM}
HEADER
  [[ -n "${SLURM_PARTITION:-}" ]] && echo "#SBATCH --partition=${SLURM_PARTITION}"
  [[ -n "${SLURM_ACCOUNT:-}" ]] && echo "#SBATCH --account=${SLURM_ACCOUNT}"
  [[ -n "${SLURM_GRES:-}" ]] && echo "#SBATCH --gres=${SLURM_GRES}"

  cat <<'BODY'
set -euo pipefail

# Project tree synced by deploy_to_cluster.sh
BODY
  emit_remote_cd

  cat <<'BODY'

# Timestamped activation dumps on scratch: prefer $SCRATCH if the site sets it.
_ts="$(date +%Y%m%d_%H%M%S)"
_jid="${SLURM_JOB_ID:-$$}"
_scratch="${SCRATCH:-/scratch/${USER}}"
export ACTIVATION_DUMP_DIR="${_scratch}/research_activation_dumps/run_${_ts}_${_jid}"
mkdir -p "${ACTIVATION_DUMP_DIR}"
echo "ACTIVATION_DUMP_DIR=${ACTIVATION_DUMP_DIR}" >&2

BODY

  if [[ -n "${CONDA_ENV:-}" ]]; then
    cat <<BODY
# Conda env ${CONDA_ENV}: refresh deps then run benchmarks
eval "\$(conda shell.bash hook 2>/dev/null)" || true
if ! command -v conda >/dev/null 2>&1; then
  echo "conda not found but CONDA_ENV is set" >&2
  exit 1
fi
conda activate ${CONDA_ENV}
pip install -r requirements.txt
BODY
  else
    cat <<BODY
# Virtualenv in project directory
${PYTHON_BIN} -m venv .venv_cluster
# shellcheck source=/dev/null
source .venv_cluster/bin/activate
python -m pip install -U pip wheel
python -m pip install -r requirements.txt
BODY
  fi

  cat <<'BODY'

echo "Running multi-model orchestrator…" >&2
python multi_model_orchestrator.py --config models_to_test.yaml
echo "Done. Results under ./results ; activations under ${ACTIVATION_DUMP_DIR}" >&2
BODY
} > "${JOB_SLURM}"

chmod +x "${JOB_SLURM}"

echo "Wrote ${JOB_SLURM}"

EXCLUDES=(
  --exclude='.venv/'
  --exclude='.venv_cluster/'
  --exclude='__pycache__/'
  --exclude='*.py[cod]'
  --exclude='.pytest_cache/'
  --exclude='.git/'
  --exclude='activation_dumps/'
  --exclude='.mypy_cache/'
)

# shellcheck disable=SC2086
rsync -avz "${EXCLUDES[@]}" ${RSYNC_EXTRA:-} \
  "${SCRIPT_DIR}/" \
  "${REMOTE_HOST}:${REMOTE_DIR}/"

echo ""
echo "Synced to ${REMOTE_HOST}:${REMOTE_DIR}"
echo "Submit on the cluster:"
echo "  ssh ${REMOTE_HOST} 'cd ${REMOTE_DIR} && sbatch job.slurm'"
